
import React, { memo, useState, useEffect, useRef, Suspense, useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeRaw from 'rehype-raw';
import Mark from 'mark.js/dist/mark.es6.js';
import { ChatMessage } from '../../../types.ts';
import { useEditorUI } from '../../../store/ui/useEditorUI.ts';
import { useGlobalUiStore } from '../../../store/useGlobalUiStore.ts';
import { ClipboardIcon, CheckIcon, SitemapIcon, ChevronDownIcon, ChevronUpIcon } from '../../common/Icons.tsx';
import { MESSAGE_CONTENT_SNIPPET_THRESHOLD } from '../../../constants.ts';
import { preprocessMessageContent } from '../../../services/utils.ts';
import { Button } from '../../ui/Button.tsx';

const CodeBlockHighlighter = React.lazy(() => import('../../common/CodeBlockHighlighter.tsx'));

interface MessageContentProps {
  message: ChatMessage;
  displayContent: string;
  highlightTerm?: string;
  isContentExpanded: boolean;
  onToggleExpansion: (messageId: string, type: 'content') => void;
  isStreaming?: boolean;
}

// --- CUSTOM TEXT PROCESSOR ---
// This function recursively traverses the React Node tree generated by ReactMarkdown.
// It finds string nodes and applies the Gold Quote formatting.
// This replaces the old method of injecting <span class="quoted-text"> HTML strings.
const processNodeContent = (nodes: React.ReactNode): React.ReactNode => {
    return React.Children.map(nodes, node => {
        if (typeof node === 'string') {
            // Regex matches text inside double quotes.
            // ("[^"\n]+") matches: quote, followed by non-quote/non-newline chars, followed by quote.
            const parts = node.split(/("[^"\n]+")/g);
            
            return parts.map((part, i) => {
                if (part.startsWith('"') && part.endsWith('"') && part.length >= 2) {
                    return <span key={i} className="quoted-text">{part}</span>;
                }
                return part;
            });
        }
        
        if (React.isValidElement(node) && (node.props as any).children) {
            // Recursively process children of elements (like strong, em, etc.)
            // We clone the element to preserve its type and other props, but replace children.
            return React.cloneElement(node, {
                children: processNodeContent((node.props as any).children)
            } as any);
        }
        
        return node;
    });
};

const markdownRenderers = {
    code({ node, inline, className, children, ...props }: any) {
        const [isCodeCopied, setIsCodeCopied] = useState(false);
        const codeString = String(children).replace(/\n$/, '');
        const { openMermaidModal } = useEditorUI.getState();
        const { message } = props.message_obj; 

        const handleCopyCode = () => {
            navigator.clipboard.writeText(codeString).then(() => {
                setIsCodeCopied(true);
                setTimeout(() => setIsCodeCopied(false), 2000);
            }).catch(err => {
                console.error('Failed to copy code: ', err);
                alert('Failed to copy code.');
            });
        };
        
        const match = /language-(\w+)/.exec(className || '');
        const lang = match ? match[1] : 'text';
        const isMermaid = lang.toLowerCase() === 'mermaid';
        const isStreaming = props.message_obj?.message?.isStreaming;

        if (!inline && match && isStreaming) {
            return (
                <div className="my-2 rounded-xl border border-gray-200 dark:border-white/10 bg-gray-50 dark:bg-zinc-900 p-2 sm:p-4 overflow-x-auto">
                    <span className="text-xs text-gray-500 dark:text-gray-400 font-mono mb-2 block animate-pulse">Generating code...</span>
                    <pre className="text-sm text-gray-800 dark:text-gray-300 font-mono m-0"><code>{codeString}</code></pre>
                </div>
            );
        }

        return !inline && match ? (
            <div className="relative group/codeblock my-2 rounded-xl shadow-sm border border-gray-200 dark:border-white/10 bg-gray-50 dark:bg-zinc-900">
                <div className="sticky top-0 z-10 flex justify-between items-center px-4 py-1.5 bg-gray-100 dark:bg-black/40 rounded-t-xl border-b border-gray-200 dark:border-white/5">
                  <span className="text-xs text-gray-600 dark:text-gray-300 font-mono">{lang}</span>
                  <div className="flex items-center space-x-2">
                    {isMermaid && (
                      <Button
                        onClick={() => openMermaidModal({ code: codeString, messageId: message.id, fullContent: message.content })}
                        title="Render Diagram"
                        aria-label="Render Mermaid diagram"
                        variant="ghost"
                        size="sm"
                        className="p-1.5 bg-gray-200 dark:bg-black/30 text-gray-600 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white opacity-0 group-hover/codeblock:opacity-100 focus:opacity-100 hover:bg-emerald-100 dark:hover:bg-emerald-500/20"
                        icon={<SitemapIcon className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />}
                      />
                    )}
                    <Button 
                        onClick={handleCopyCode} 
                        title={isCodeCopied ? "Copied!" : "Copy code"} 
                        aria-label={isCodeCopied ? "Copied code to clipboard" : "Copy code to clipboard"} 
                        variant="ghost"
                        size="sm"
                        className="p-1.5 bg-gray-200 dark:bg-black/30 text-gray-600 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white opacity-0 group-hover/codeblock:opacity-100 focus:opacity-100 hover:bg-gray-300 dark:hover:bg-white/20"
                        icon={isCodeCopied ? <CheckIcon className="w-4 h-4 text-emerald-600 dark:text-emerald-400" /> : <ClipboardIcon className="w-4 h-4" />}
                    />
                  </div>
                </div>
                <div className="overflow-hidden rounded-b-xl">
                    <Suspense fallback={<div className="p-4 text-xs text-gray-500 dark:text-gray-400 font-mono">Loading code view...</div>}>
                        <CodeBlockHighlighter language={lang} codeString={codeString} />
                    </Suspense>
                </div>
            </div>
        ) : (
            // This styling ensures the "Purple Glowing" effect for inline code/tags
            <code className="bg-gray-100 dark:bg-zinc-800 text-emerald-600 dark:text-emerald-400 rounded-md font-mono border border-gray-200 dark:border-white/10 px-1 py-0.5 break-all whitespace-pre-wrap" {...props}>{children}</code>
        );
    },
    a(props: any) { return <a target="_blank" rel="noopener noreferrer" {...props} />; }
};

const remarkPluginsList = [remarkGfm];
const rehypePluginsList = [rehypeRaw];

const MessageContent: React.FC<MessageContentProps> = memo(({ message, displayContent, highlightTerm, isContentExpanded, onToggleExpansion, isStreaming }) => {
    const markdownContentRef = useRef<HTMLDivElement>(null);
    const chatFontSizeLevel = useGlobalUiStore(state => state.chatFontSizeLevel);
    
    // Process content to handle custom headers and tags (but NOT quotes anymore)
    const processedContent = useMemo(() => {
        return preprocessMessageContent(displayContent);
    }, [displayContent]);

    const isLongTextContent = processedContent.trim().length > MESSAGE_CONTENT_SNIPPET_THRESHOLD;
    const contentToRender = (isLongTextContent && !isContentExpanded) ? processedContent.trim().substring(0, MESSAGE_CONTENT_SNIPPET_THRESHOLD) + "..." : processedContent;

    useEffect(() => {
        if (message.isGithubContextMessage || isStreaming) return; 
        if (markdownContentRef.current) {
          const instance = new Mark(markdownContentRef.current);
          instance.unmark({ done: () => { if (highlightTerm && highlightTerm.trim() !== "") { instance.mark(highlightTerm, { element: "mark", className: "highlighted-text", exclude: ["pre *", "code *", "pre", "code"], separateWordSearch: false, accuracy: "partially", wildcards: "disabled" }); } } });
        }
    }, [highlightTerm, contentToRender, isContentExpanded, message.isGithubContextMessage, isStreaming]);

    const getFontSizeClass = (level: number) => {
        switch (level) {
            case 0: return 'text-xs';
            case 1: return 'text-sm';
            case 2: return 'text-base';
            case 3: return 'text-lg';
            case 4: return 'text-xl';
            default: return 'text-sm';
        }
    };

    const fontSizeClass = getFontSizeClass(chatFontSizeLevel);

    // Memoize the markdown components to prevent complete DOM teardown/rebuild on every keystroke during streaming
    const memoizedComponents = useMemo(() => {
        return {
            ...markdownRenderers, 
            code: (props: any) => markdownRenderers.code({...props, message_obj: {message}}),
            p: ({ node, children, ...props }: any) => <div {...props}>{isStreaming ? children : processNodeContent(children)}</div>,
            li: ({ node, children, ...props }: any) => <li {...props}>{isStreaming ? children : processNodeContent(children)}</li>,
            blockquote: ({ node, children, ...props }: any) => <blockquote {...props}>{isStreaming ? children : processNodeContent(children)}</blockquote>,
            div: ({ node, children, ...props }: any) => <div {...props}>{isStreaming ? children : processNodeContent(children)}</div>
        };
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [message.id, isStreaming]);

    if (!contentToRender.trim()) return null;

    return (
        <>
            <div id={`message-content-${message.id}`} ref={markdownContentRef} className={`${fontSizeClass} markdown-content break-words transition duration-200`}>
                <ReactMarkdown 
                    remarkPlugins={remarkPluginsList} 
                    rehypePlugins={rehypePluginsList} 
                    components={memoizedComponents}
                >
                    {contentToRender}
                </ReactMarkdown>
            </div>
            {isLongTextContent && (
                <Button 
                    onClick={() => onToggleExpansion(message.id, 'content')} 
                    variant="ghost"
                    size="sm"
                    className="text-emerald-600 dark:text-emerald-400 hover:text-emerald-700 dark:hover:text-emerald-300 mt-1.5 px-0 py-0 hover:bg-transparent" 
                    aria-expanded={isContentExpanded}
                >
                    {isContentExpanded ? "Show less" : "Show more"}
                    {isContentExpanded ? (<ChevronUpIcon className="w-3.5 h-3.5 ml-1" />) : (<ChevronDownIcon className="w-3.5 h-3.5 ml-1" />)}
                </Button>
            )}
        </>
    );
});

export default MessageContent;
